name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]
    paths:
      - 'worker/**'
      - '.github/workflows/deploy-worker.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Wrangler
        run: |
          npm install -g wrangler@3

      - name: Publish Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          cd worker
          echo "name = \"sparrow-ai-hero-proxy\"" > wrangler.toml
          echo "main = \"index.js\"" >> wrangler.toml
          echo "compatibility_date = \"2024-10-01\"" >> wrangler.toml
          echo "[vars]" >> wrangler.toml
          echo "GEMINI_API_KEY = \"$GEMINI_API_KEY\"" >> wrangler.toml
          wrangler publish --account-id "$CLOUDFLARE_ACCOUNT_ID" --var GEMINI_API_KEY

